SELECT 
    b.TITLE, 
    a.BOARD_ID, 
    a.REPLY_ID, 
    a.WRITER_ID,
    a.CONTENTS,
    a.CREATED_DATE
FROM USED_GOODS_REPLY a
    inner join USED_GOODS_BOARD b on a.BOARD_ID=b.BOARD_ID
WHERE YEAR(b.CREATED_DATE)=2022 and MONTH(b.CREATED_DATE)=10
ORDER BY a.CREATED_DATE, b.TITLE;